<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="ForwardArrayListIterator" Id="{7968eb7c-7972-4d7e-9326-30fe1b3e84f7}" SpecialFunc="None">
    <Declaration><![CDATA[(*

## Short summary

This class can be used as a simple iterator for array lists. It iterates from first element to last element.

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2024 ekvip automation GmbH <info@ekvip.de>
| SPDX-License-Identifier: Apache-2.0
| For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

.. </legal notes>



*)

{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ForwardArrayListIterator EXTENDS AbstractArrayListIterator
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="className" Id="{19eb376d-73fa-434f-98ef-ec8e8601cfa9}">
      <Declaration><![CDATA[PROPERTY className :CNM_AbstractObject.ClassName]]></Declaration>
      <Get Name="Get" Id="{b2932461-54ba-4ea8-9512-ed0c3c42ff29}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[className := 'ForwardArrayListIterator';
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{a9ac3143-e583-4073-a9b1-56d6144aea86}">
      <Declaration><![CDATA[(*

## Short summary

The constructor ``FB_init`` is needed to create an unique hash code.
The hash code is a pseudo random number create with a [xorshift](https://en.wikipedia.org/wiki/Xorshift) algorithm.
It can be overwritten on derivations, because it will be called implicit, ``SUPER^.FB_init()`` is not required.
For more information check: [Behavoir with derived function blocks](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/5482088715.html?id=6983869892358031022).

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2022 ekvip automation GmbH <info@ekvip.de>
| SPDX-License-Identifier: Apache-2.0
| For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

.. </legal notes>



*)
METHOD FB_init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change) *)
	bInCopyCode	: BOOL;
	(* the array list which should be iterated, can be 0 *)
	arrayList :REFERENCE TO ArrayList;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.direction := IterationDirection.FORWARD;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="ForwardArrayListIterator">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="ForwardArrayListIterator.className.Get">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="ForwardArrayListIterator.FB_init">
      <LineId Id="1" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>