<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="ForwardLinkedListIterator" Id="{c17e9c50-df90-49e0-9020-8a564ff1e9c0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ForwardLinkedListIterator EXTENDS AbstractLinkedListIterator
VAR	
	lastChangeVersion :__XWORD;
	lastExecute :BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	]]></ST>
    </Implementation>
    <Property Name="className" Id="{e0adba75-a5b5-44d7-8d7a-d49a52d0d654}">
      <Declaration><![CDATA[PROPERTY className :CNM_AbstractObject.ClassName]]></Declaration>
      <Get Name="Get" Id="{06e74eab-8e23-4d32-b683-fc8d3c84e376}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[className := 'ForwardLinkedListIterator';
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{2422ea58-5484-4bba-8527-c4a13e6e4003}">
      <Declaration><![CDATA[(*

## Short summary

The constructor ``FB_init`` is needed to create an unique hash code.
The hash code is a pseudo random number create with a [xorshift](https://en.wikipedia.org/wiki/Xorshift) algorithm.
It can be overwritten on derivations, because it will be called implicit, ``SUPER^.FB_init()`` is not required.
For more information check: [Behavoir with derived function blocks](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/5482088715.html?id=6983869892358031022).

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2022 ekvip automation GmbH <info@ekvip.de>
| SPDX-License-Identifier: Apache-2.0
| For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

.. </legal notes>



*)
METHOD FB_init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change) *)
	bInCopyCode	: BOOL;
	(* list that is used to iterate*)
	list :REFERENCE TO LinkedList;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.direction := IterationDirection.FORWARD;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="ForwardLinkedListIterator">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="ForwardLinkedListIterator.className.Get">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="ForwardLinkedListIterator.FB_init">
      <LineId Id="1" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>