<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="InverseLinkedListIterator" Id="{36616ea9-1ec8-450e-9b6f-1a219853a3c0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK InverseLinkedListIterator EXTENDS AbstractLinkedListIterator
VAR	
	lastChangeVersion :__XWORD;
	lastExecute :BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="className" Id="{ce45103f-2d0e-4ea1-9bb6-98ba8d53ef22}">
      <Declaration><![CDATA[PROPERTY className :CNM_AbstractObject.ClassName]]></Declaration>
      <Get Name="Get" Id="{9228fcb9-a7c9-4a49-a529-1050c0d9a9f5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[className := 'InverseLinkedListIterator';
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{ab00751c-0cae-4fbf-9dd9-a417acdac38a}">
      <Declaration><![CDATA[(*

## Short summary

The constructor ``FB_init`` is needed to create an unique hash code.
The hash code is a pseudo random number create with a [xorshift](https://en.wikipedia.org/wiki/Xorshift) algorithm.
It can be overwritten on derivations, because it will be called implicit, ``SUPER^.FB_init()`` is not required.
For more information check: [Behavoir with derived function blocks](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/5482088715.html?id=6983869892358031022).

.. <legal notes>

legal notes
=================
| SPDX-FileCopyrightText: © 2022 ekvip automation GmbH <info@ekvip.de>
| SPDX-License-Identifier: Apache-2.0
| For details check: Apache-2.0_

.. _Apache-2.0: https://www.apache.org/licenses/LICENSE-2.0

.. </legal notes>



*)
METHOD FB_init : BOOL
VAR_INPUT
	(* if TRUE, the retain variables are initialized (warm start / cold start)*)
	bInitRetains	: BOOL;
	(* if TRUE, the instance afterwards gets moved into the copy code (online change) *)
	bInCopyCode	: BOOL;
	(* list that is used to iterate*)
	list :REFERENCE TO LinkedList;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.direction := IterationDirection.BACKWARD;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="InverseLinkedListIterator">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="InverseLinkedListIterator.className.Get">
      <LineId Id="1" Count="1" />
    </LineIds>
    <LineIds Name="InverseLinkedListIterator.FB_init">
      <LineId Id="1" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>